#pragma once

#include <utils/math_utils.h>
#include <array>
#include <functional>
#include <kinematics.h>
#include <message_types.h>
#include <gait_tuned.h>

static constexpr float default_offset[6] = {0, 0.52, 0.08, 0.58, 0.16, 0.66};
static constexpr float default_stand_frac = 3.1 / 6;

struct gait_state_t {
    float step_height, step_x, step_y, step_angle, step_speed, step_depth, stand_frac;
    GaitType gait_type;
    float offset[6];
    // Explicit cadence in cycles/s. 0 = use the legacy stride-derived law below. The searched gaits
    // set it, because that law and the one they were optimized under disagree -- mildly when walking
    // forward (0.90-1.24x) and by 1.80x for an in-place turn, where the legacy CLIP floors cadence
    // at 0.75 cyc/s and the tuned gait wants 1.35. Last member, so existing aggregate initializers
    // stay valid and zero it.
    float phase_rate;
};

// Deadbands for "the gait is commanded to move". Stride is millimetres of foot travel; yaw is
// radians of body rotation per stance, and 0.005 rad across the 171 mm leg radius is 0.9 mm of foot
// travel -- the same order as the stride deadband. step_angle used to be tested against exact zero,
// which the command ramp below never reaches, so a single turn command left the cycle stepping in
// place for as long as the robot stayed powered.
static constexpr float GAIT_STRIDE_DEADBAND_MM = 2.0f;
static constexpr float GAIT_YAW_DEADBAND_RAD = 0.005f;

inline bool gaitIsCommanded(const gait_state_t& gait) {
    return std::fabs(gait.step_x) >= GAIT_STRIDE_DEADBAND_MM || std::fabs(gait.step_y) >= GAIT_STRIDE_DEADBAND_MM ||
           std::fabs(gait.step_angle) >= GAIT_YAW_DEADBAND_RAD;
}

// Stick -> command ranges for GaitType::TUNED. The searched gait is a velocity->gait map, so the
// stick becomes a velocity command over the envelope the search actually covered; commanding outside
// it asks for a gait nobody measured. These mirror CMD_VX/CMD_VY/CMD_YAW in hexapod_mj_env.py.
// They live here rather than in gait_tuned.h because that file is regenerated by
// simulation/export_gait.py, and rather than in MotionService because the host gait tests need them.
static constexpr float TUNED_CMD_VX_MAX = 0.45f;   // m/s forward
static constexpr float TUNED_CMD_VY_MAX = 0.12f;   // m/s lateral
static constexpr float TUNED_CMD_YAW_MAX = 1.0f;   // rad/s
// The s1 slider trims foot lift around tuned_gait::STEP_HEIGHT_MM rather than setting it from zero,
// so the operator keeps authority without discarding the parameter the terrain search cared most
// about. Note the trim is not symmetric in feasibility: the bottom stop is the only fully reachable
// setting, while the top stop exceeds femur travel at every stride.
static constexpr float TUNED_LIFT_TRIM_MM = 15.0f;

static constexpr float GAIT_SNAP_MM = 0.01f;
static constexpr float GAIT_SNAP_RAD = 1e-5f;
static constexpr float GAIT_SNAP_RATE = 1e-4f;
static constexpr float GAIT_SNAP_DEPTH = 1e-6f;

inline float approachf(float current, float target, float alpha, float eps) {
    const float next = lerpf(current, target, alpha);
    return std::fabs(target - next) <= eps ? target : next;
}

// Picks a gait from the commanded stride, slow and stable up to fast and sparse. The bands overlap
// by AUTO_HYSTERESIS so a stick held near a boundary does not oscillate between two schedules.
inline GaitType selectAutoGait(float speed01, GaitType current) {
    constexpr float RIPPLE_MAX = 0.30f, TRI_MAX = 0.70f, AUTO_HYSTERESIS = 0.06f;
    const float rippleMax = current == GaitType::RIPPLE ? RIPPLE_MAX + AUTO_HYSTERESIS : RIPPLE_MAX;
    const float triMax = current == GaitType::BI_GATE ? TRI_MAX - AUTO_HYSTERESIS : TRI_MAX;
    if (speed01 < rippleMax) return GaitType::RIPPLE;
    if (speed01 < triMax) return GaitType::TRI_GATE;
    return GaitType::BI_GATE;
}

inline void approachGaitCommand(gait_state_t& current, const gait_state_t& target, float dt, float tau) {
    const float a = (tau <= 0.0f || dt <= 0.0f) ? 1.0f : 1.0f - expf(-dt / tau);
    current.step_x = approachf(current.step_x, target.step_x, a, GAIT_SNAP_MM);
    current.step_y = approachf(current.step_y, target.step_y, a, GAIT_SNAP_MM);
    current.step_angle = approachf(current.step_angle, target.step_angle, a, GAIT_SNAP_RAD);
    current.step_speed = approachf(current.step_speed, target.step_speed, a, GAIT_SNAP_RATE);
    current.step_height = approachf(current.step_height, target.step_height, a, GAIT_SNAP_MM);
    current.step_depth = approachf(current.step_depth, target.step_depth, a, GAIT_SNAP_DEPTH);
    // phase_rate 0 means "derive cadence from stride", not "stand still", so ramping across that
    // boundary would spend the whole transition at cadences neither law asks for. Ease only between
    // two explicit rates; otherwise switch outright.
    current.phase_rate = (current.phase_rate > 0.0f && target.phase_rate > 0.0f)
                             ? approachf(current.phase_rate, target.phase_rate, a, GAIT_SNAP_RATE)
                             : target.phase_rate;
}

class GaitController {
  private:
    float phase = 0.0f;
    float defaultPosition[6][4] = {{122, 152, -66, 1},  {171, 0, -66, 1},  {122, -152, -66, 1},
                                   {-122, 152, -66, 1}, {-171, 0, -66, 1}, {-122, -152, -66, 1}};
    float targetDefaultPosition[6][4] = {{122, 152, -66, 1},  {171, 0, -66, 1},  {122, -152, -66, 1},
                                         {-122, 152, -66, 1}, {-171, 0, -66, 1}, {-122, -152, -66, 1}};
    float swingStartPosition[6][4] = {{122, 152, -66, 1},  {171, 0, -66, 1},  {122, -152, -66, 1},
                                      {-122, 152, -66, 1}, {-171, 0, -66, 1}, {-122, -152, -66, 1}};
    bool footWasSwinging[6] = {false, false, false, false, false, false};
    static constexpr uint8_t BEZIER_POINTS = 12;
    static constexpr std::array<float, BEZIER_POINTS> COMBINATORIAL_VALUES = {
        combinatorial_constexpr(11, 0),  // 1
        combinatorial_constexpr(11, 1),  // 11
        combinatorial_constexpr(11, 2),  // 55
        combinatorial_constexpr(11, 3),  // 165
        combinatorial_constexpr(11, 4),  // 330
        combinatorial_constexpr(11, 5),  // 462
        combinatorial_constexpr(11, 6),  // 462
        combinatorial_constexpr(11, 7),  // 330
        combinatorial_constexpr(11, 8),  // 165
        combinatorial_constexpr(11, 9),  // 55
        combinatorial_constexpr(11, 10), // 11
        combinatorial_constexpr(11, 11)  // 1
    };

    alignas(32) static constexpr float BEZIER_STEPS[12] = {-1.0f, -1.4f, -1.5f, -1.5f, -1.5f, 0.0f,
                                                           0.0f,  0.0f,  1.5f,  1.5f,  1.4f,  1.0f};

    alignas(32) static constexpr float BEZIER_HEIGHTS[12] = {0.0f, 0.0f, 0.9f, 0.9f, 0.9f, 0.9f,
                                                             0.9f, 1.1f, 1.1f, 1.1f, 0.0f, 0.0f};

    void stanceCurve(const float length, const float angle, const float* depth, const float phase, float* point) {
        float step = length * (1.0f - 2.0f * phase);
        point[0] += step * std::cos(angle);
        point[1] += step * std::sin(angle);

        if (length != 0.0f) {
            point[2] = *depth * std::cos((M_PI * (point[0] + point[1])) / (2.f * length));
        }
    }

    void bezierCurve(const float length, const float angle, const float* height, const float phase, float* point) {
        const float X_POLAR = std::cos(angle);
        const float Z_POLAR = std::sin(angle);

        float phase_power = 1.0f;
        float inv_phase_power = std::pow(1.0f - phase, 11);
        const float one_minus_phase = 1.0f - phase;

        for (int i = 0; i < 12; i++) {
            float b = COMBINATORIAL_VALUES[i] * phase_power * inv_phase_power;
            point[0] += b * BEZIER_STEPS[i] * length * X_POLAR;
            point[1] += b * BEZIER_STEPS[i] * length * Z_POLAR;
            point[2] += b * BEZIER_HEIGHTS[i] * *height;

            phase_power *= phase;
            inv_phase_power /= one_minus_phase;
        }
    }

    void advancePhase(float dt, float velocity) { phase = std::fmod(phase + dt * velocity, 1.0f); }

    std::tuple<float, std::function<void(const float, const float, const float*, const float, float*)>, float>
    phaseParams(float phase, float standFrac, float depth, float height) {
        if (phase < standFrac) {
            return {phase / standFrac,
                    [this](const float l, const float a, const float* d, const float p, float* pt) {
                        this->stanceCurve(l, a, d, p, pt);
                    },
                    -depth};
        }
        return {(phase - standFrac) / (1 - standFrac),
                [this](const float l, const float a, const float* h, const float p, float* pt) {
                    this->bezierCurve(l, a, h, p, pt);
                },
                height};
    }

    bool positionsMatch(const float lhs[6][4], const float rhs[6][4], float epsilon = 0.5f) const {
        for (int i = 0; i < 6; ++i) {
            for (int j = 0; j < 4; ++j) {
                if (std::fabs(lhs[i][j] - rhs[i][j]) > epsilon) return false;
            }
        }
        return true;
    }

    bool footAtTarget(int footIndex, float epsilon = 0.5f) const {
        for (int j = 0; j < 4; ++j) {
            if (std::fabs(defaultPosition[footIndex][j] - targetDefaultPosition[footIndex][j]) > epsilon) return false;
        }
        return true;
    }

    void updateDefaultPositionTarget(int footIndex, float swingProgress) {
        for (int j = 0; j < 4; ++j) {
            defaultPosition[footIndex][j] =
                lerpf(swingStartPosition[footIndex][j], targetDefaultPosition[footIndex][j], swingProgress);
        }
    }

  public:
    GaitController() {}

    void setDefaultFootTarget(const float target[6][4]) { COPY_2D_ARRAY_6x4(targetDefaultPosition, target); }

    void snapDefaultFootTarget(const float target[6][4]) {
        COPY_2D_ARRAY_6x4(defaultPosition, target);
        COPY_2D_ARRAY_6x4(targetDefaultPosition, target);
        COPY_2D_ARRAY_6x4(swingStartPosition, target);
        for (bool &footSwinging : footWasSwinging) footSwinging = false;
        phase = 0.0f;
    }

    bool hasPendingStanceChange() const { return !positionsMatch(defaultPosition, targetDefaultPosition); }

    void setGait(gait_state_t& gait) {
        switch (gait.gait_type) {
            case GaitType::TRI_GATE:
                gait.offset[0] = 0.0f;
                gait.offset[1] = 0.52f;
                gait.offset[2] = 0.08f;
                gait.offset[3] = 0.58f;
                gait.offset[4] = 0.16f;
                gait.offset[5] = 0.66f;
                gait.stand_frac = 3.1f / 6.0f;
                break;
            case GaitType::BI_GATE:
                gait.offset[0] = 0.0f;
                gait.offset[1] = 1.0f / 3.0f;
                gait.offset[2] = 2.0f / 3.0f;
                gait.offset[3] = 2.0f / 3.0f;
                gait.offset[4] = 1.0f / 3.0f;
                gait.offset[5] = 0.0f;
                gait.stand_frac = 2.1f / 6.0f;
                break;
            case GaitType::WAVE:
                gait.offset[0] = 0.0f;
                gait.offset[1] = 1.0f / 6.0f;
                gait.offset[2] = 2.0f / 6.0f;
                gait.offset[3] = 5.0f / 6.0f;
                gait.offset[4] = 4.0f / 6.0f;
                gait.offset[5] = 3.0f / 6.0f;
                gait.stand_frac = 5.0f / 6.0f;
                break;
            case GaitType::RIPPLE:
                gait.offset[0] = 0.0f;
                gait.offset[1] = 4.0f / 6.0f;
                gait.offset[2] = 2.0f / 6.0f;
                gait.offset[3] = 1.0f / 6.0f;
                gait.offset[4] = 5.0f / 6.0f;
                gait.offset[5] = 3.0f / 6.0f;
                gait.stand_frac = 5.0f / 6.0f;
                break;
            case GaitType::TUNED:
                // Searched coordination; the caller must also apply tuned_gait::STEP_HEIGHT_MM,
                // STEP_DEPTH_MM and RIDE_MM, which is what MotionService's WALK branch does.
                for (uint8_t i = 0; i < 6; ++i) gait.offset[i] = tuned_gait::OFFSET[i];
                gait.stand_frac = tuned_gait::STAND_FRAC;
                break;
            default: break;
        }
    }


    // repositioning: a stance-change cycle with no locomotion command, where feet already on
    // target hold station instead of stepping. Plain walking cycles pass false.
    void generateFeet(gait_state_t& gait, BodyStateMsg& body, bool repositioning = false) {
        float newFeet[6][4];
        COPY_2D_ARRAY_6x4(newFeet, defaultPosition);

        for (int i = 0; i < 6; i++) {
            const float ph = std::fmod(this->phase + gait.offset[i], 1.0f);
            const bool isSwinging = ph >= gait.stand_frac;
            // A foot already standing where it belongs has nothing to fetch, so it holds station
            // rather than taking an empty step while the others catch up. Repositioning only: in
            // normal walking every foot sits at its default position and must still swing.
            const bool holdStation = repositioning && footAtTarget(i);

            if (isSwinging && !footWasSwinging[i]) {
                for (int j = 0; j < 4; ++j) {
                    swingStartPosition[i][j] = defaultPosition[i][j];
                }
            }
            footWasSwinging[i] = isSwinging;

            if (isSwinging && !holdStation) {
                const float swingProgress = (ph - gait.stand_frac) / (1.0f - gait.stand_frac);
                updateDefaultPositionTarget(i, swingProgress);
            }

            const float rx = defaultPosition[i][0];
            const float ry = defaultPosition[i][1];
            const float strokeX = gait.step_x + gait.step_angle * (-ry);
            const float strokeY = gait.step_y + gait.step_angle * (rx);
            const float stroke = std::hypot(strokeX, strokeY);
            const float direction = std::atan2(strokeY, strokeX);

            float delta[3] = {0, 0, 0};
            if (!holdStation) {
                auto [phNorm, curveFn, amp] = phaseParams(ph, gait.stand_frac, gait.step_depth, gait.step_height);
                curveFn(stroke / 2, direction, &amp, phNorm, delta);
            }

            for (int j = 0; j < 3; j++) {
                newFeet[i][j] = defaultPosition[i][j] + delta[j];
            }
            newFeet[i][3] = 1;
        }

        body.updateFeet(newFeet);
    }

    void setPhase(float p) { phase = std::fmod(p, 1.0f); }
    float getPhase() const { return phase; }

    void step(gait_state_t& gait, BodyStateMsg& body, float dt) {
        const bool isMoving = gaitIsCommanded(gait);
        const bool isRepositioning = !isMoving && hasPendingStanceChange();

        if (!isMoving && !isRepositioning) {
            for (int i = 0; i < 6; i++) {
                for (int j = 0; j < 4; j++) {
                    body.feet[i][j] += (defaultPosition[i][j] - body.feet[i][j]) * dt * 10.0f;
                }
            }
            phase = 0;
            return;
        }

        const float length = std::hypot(gait.step_x, gait.step_y) * (gait.step_x < 0 ? -1 : 1);
        const float speed_factor = std::max(std::abs(length) / 25.f, std::abs(gait.step_angle) * 1.5f);
        const float speed =
            isRepositioning ? gait.step_speed
            : gait.phase_rate > 0.f ? gait.phase_rate
                                    : gait.step_speed * CLIP(speed_factor, 0.75, 1.5f);

        advancePhase(dt, speed);
        generateFeet(gait, body, isRepositioning);
    }
};
