#pragma once

#include <cmath>   // sqrtf / fabsf in velocity_to_gait; do not rely on the includer providing it

// GENERATED by simulation/export_gait.py on 2026-09-28 -- do not edit by hand.
// Source: simulation/src/resources/gait_library.json key '__single___wide3'
// Search:  cma, budget 1280, command set 'wide', held-out score 0.912
//
// These are the open-loop gait constants found by CMA-ES over the terrain suite. They need no
// policy: on the sim benchmark this gait scores ~0.98/0.96/0.93/0.77 at 0/40/80/120 mm roughness
// against ~0.66/0.38/0.17/0.12 for the shipped tripod, and clears a 140 mm step cleanly.
// Servo margin was checked: at HALF the modelled stall torque it still retains 93% of its score
// (the shipped gait retains 88%), with no falls in 1512 episodes.
//
// The dominant term is FOOT LIFT: 68.2 mm here against the 15 mm default. GaitType::TUNED
// uses it as the centre of the s1 lift trim (motion.h), not the legacy (s1+1)*20 mapping.

namespace tuned_gait {

// --- coordination (feed these into gait_state_t) ---
constexpr float STAND_FRAC = 0.500313f;              // stance fraction of the cycle
constexpr float OFFSET[6] = {0.000000f, 0.485762f, 0.971525f, 0.478937f, 0.958527f, 0.438118f};

// --- foot trajectory / posture ---
constexpr float STEP_HEIGHT_MM = 68.2472f;         // needs STEP_HEIGHT_MAX_MM >= this
constexpr float STEP_DEPTH_MM = 1.868632f;     // stance-phase downward push (traction)
constexpr float RIDE_MM = 18.8152f;              // + raises the body: body_state.zm = -RIDE_MM

// --- action-scale constants this gait assumes (mirror of hexapod_mj_env) ---
constexpr float STEP_XY_MM = 100.0f;              // joystick [-1,1] -> step_x / step_y (mm)
constexpr float STEP_ANGLE_RAD = 0.8f;       // joystick [-1,1] -> step_angle (rad)
constexpr float STEP_HEIGHT_MIN_MM = 10.0f, STEP_HEIGHT_MAX_MM = 80.0f;
constexpr float PHASE_RATE_MIN = 0.0f, PHASE_RATE_MAX = 3.5f;  // cyc/s

// --- velocity-command gains, used by velocity_to_gait in the GaitType::TUNED WALK branch ---
// cmd = [vx forward m/s, vy lateral m/s, yaw rad/s]; the robot faces +Y, so vx drives step_y.
constexpr float GX0 = 0.269029f, GX1 = 0.213827f;      // forward-axis stride gain, slow/fast
constexpr float GY0 = 0.503691f, GY1 = 0.341345f;      // lateral-axis stride gain
constexpr float GYAW0 = 2.273614f, GYAW1 = 1.663115f;
constexpr float BLEND_SPEED = 0.279279f;          // m/s at which the fast gains take over
constexpr float PR_BASE = -0.324986f, PR_SLOPE = 0.928120f, PR_YAW = 0.191999f;
constexpr float YAW_COMP = 0.027392f;

// Port of GaitSchedule.gait_action: velocity command -> normalized gait params in [-1,1].
// out = [step_x, step_y, step_angle, step_height, blend, phase_rate]; decode with the scales above.
inline float clip1(float v) { return v > 1.f ? 1.f : (v < -1.f ? -1.f : v); }

inline void velocity_to_gait(const float cmd[3], float out[6]) {
    const float vx = cmd[0], vy = cmd[1], yaw = cmd[2];
    const float speed = sqrtf(vx * vx + vy * vy);
    float b = speed / BLEND_SPEED;
    if (b > 1.f) b = 1.f;
    const float gx = GX0 + (GX1 - GX0) * b;
    const float gy = GY0 + (GY1 - GY0) * b;
    const float gyaw = GYAW0 + (GYAW1 - GYAW0) * b;
    out[0] = clip1(vy / gy);                       // step_x  = body-X = lateral
    out[1] = clip1(vx / gx);                       // step_y  = body-Y = forward
    out[2] = clip1(yaw / gyaw + YAW_COMP * vx);
    out[3] = 0.664207f;                 // normalized step height
    out[4] = b * 2.f - 1.f;
    out[5] = clip1(PR_BASE + PR_SLOPE * speed + PR_YAW * fabsf(yaw));
}

}  // namespace tuned_gait
