"""Emit a searched gait from gait_library.json as a firmware header.

The gait constants are the highest-value result of the terrain study and they need no neural
network -- but hand-copying 18 floats into `gait.h` is exactly how sim and firmware drift apart.
This generates them instead, so `firmware/include/gait_tuned.h` is a build artifact of the search.

  python export_gait.py --key __single___wide3
  python export_gait.py --key flat_tripod --out ../firmware/include/gait_tuned.h

How the firmware consumes them (GaitType::TUNED):
  * `stand_frac` and `offset[6]` -> GaitController::setGait's TUNED case (gait.h)
  * the g*/pr_* gains -> velocity_to_gait, which MotionService's WALK branch (motion.h) feeds with
    the stick scaled to a velocity command, and decodes into stride, turn and cadence
  * `step_height` -> the lift the s1 slider trims around, clipped to STEP_HEIGHT_MIN/MAX_MM
  * `step_depth`, `ride_mm` -> plain assignments in the same branch
"""

import argparse
import json
import os
from datetime import date

import numpy as np

from src.envs.hexapod_mj_env import PG_HEIGHT, PG_PHASE_RATE, PG_STEP_ANGLE, PG_STEP_XY
from src.robot.firmware_gait import TUNED_GAIT_KEY
from src.robot.gait_schedule import GaitSchedule

LIB = os.path.join(os.path.dirname(__file__), "src", "resources", "gait_library.json")
OUT = os.path.join(os.path.dirname(__file__), "..", "firmware", "include", "gait_tuned.h")


def emit(key, entry, path):
    s = GaitSchedule.from_dict(entry["params"])
    off = s.offsets()
    lift_mm = float(np.interp(s.step_height, [-1, 1], PG_HEIGHT))
    prov = (f"{entry.get('optimizer', '?')}, budget {entry.get('budget', '?')}, "
            f"command set '{entry.get('command_set', '?')}', "
            f"held-out score {entry.get('val_score', float('nan')):.3f}")

    body = f"""#pragma once

#include <cmath>   // sqrtf / fabsf in velocity_to_gait; do not rely on the includer providing it

// GENERATED by simulation/export_gait.py on {date.today().isoformat()} -- do not edit by hand.
// Source: simulation/src/resources/gait_library.json key '{key}'
// Search:  {prov}
//
// These are the open-loop gait constants found by CMA-ES over the terrain suite. They need no
// policy: on the sim benchmark this gait scores ~0.98/0.96/0.93/0.77 at 0/40/80/120 mm roughness
// against ~0.66/0.38/0.17/0.12 for the shipped tripod, and clears a 140 mm step cleanly.
// Servo margin was checked: at HALF the modelled stall torque it still retains 93% of its score
// (the shipped gait retains 88%), with no falls in 1512 episodes.
//
// The dominant term is FOOT LIFT: {lift_mm:.1f} mm here against the 15 mm default. GaitType::TUNED
// uses it as the centre of the s1 lift trim (motion.h), not the legacy (s1+1)*20 mapping.

namespace tuned_gait {{

// --- coordination (feed these into gait_state_t) ---
constexpr float STAND_FRAC = {s.duty:.6f}f;              // stance fraction of the cycle
constexpr float OFFSET[6] = {{{', '.join(f'{o:.6f}f' for o in off)}}};

// --- foot trajectory / posture ---
constexpr float STEP_HEIGHT_MM = {lift_mm:.4f}f;         // needs STEP_HEIGHT_MAX_MM >= this
constexpr float STEP_DEPTH_MM = {s.step_depth:.6f}f;     // stance-phase downward push (traction)
constexpr float RIDE_MM = {s.ride_mm:.4f}f;              // + raises the body: body_state.zm = -RIDE_MM

// --- action-scale constants this gait assumes (mirror of hexapod_mj_env) ---
constexpr float STEP_XY_MM = {PG_STEP_XY}f;              // joystick [-1,1] -> step_x / step_y (mm)
constexpr float STEP_ANGLE_RAD = {PG_STEP_ANGLE}f;       // joystick [-1,1] -> step_angle (rad)
constexpr float STEP_HEIGHT_MIN_MM = {PG_HEIGHT[0]}f, STEP_HEIGHT_MAX_MM = {PG_HEIGHT[1]}f;
constexpr float PHASE_RATE_MIN = {PG_PHASE_RATE[0]}f, PHASE_RATE_MAX = {PG_PHASE_RATE[1]}f;  // cyc/s

// --- velocity-command gains, used by velocity_to_gait in the GaitType::TUNED WALK branch ---
// cmd = [vx forward m/s, vy lateral m/s, yaw rad/s]; the robot faces +Y, so vx drives step_y.
constexpr float GX0 = {s.gx0:.6f}f, GX1 = {s.gx1:.6f}f;      // forward-axis stride gain, slow/fast
constexpr float GY0 = {s.gy0:.6f}f, GY1 = {s.gy1:.6f}f;      // lateral-axis stride gain
constexpr float GYAW0 = {s.gyaw0:.6f}f, GYAW1 = {s.gyaw1:.6f}f;
constexpr float BLEND_SPEED = {s.blend_speed:.6f}f;          // m/s at which the fast gains take over
constexpr float PR_BASE = {s.pr_base:.6f}f, PR_SLOPE = {s.pr_slope:.6f}f, PR_YAW = {s.pr_yaw:.6f}f;
constexpr float YAW_COMP = {s.yaw_comp:.6f}f;

// Port of GaitSchedule.gait_action: velocity command -> normalized gait params in [-1,1].
// out = [step_x, step_y, step_angle, step_height, blend, phase_rate]; decode with the scales above.
inline float clip1(float v) {{ return v > 1.f ? 1.f : (v < -1.f ? -1.f : v); }}

inline void velocity_to_gait(const float cmd[3], float out[6]) {{
    const float vx = cmd[0], vy = cmd[1], yaw = cmd[2];
    const float speed = sqrtf(vx * vx + vy * vy);
    float b = speed / BLEND_SPEED;
    if (b > 1.f) b = 1.f;
    const float gx = GX0 + (GX1 - GX0) * b;
    const float gy = GY0 + (GY1 - GY0) * b;
    const float gyaw = GYAW0 + (GYAW1 - GYAW0) * b;
    out[0] = clip1(vy / gy);                       // step_x  = body-X = lateral
    out[1] = clip1(vx / gx);                       // step_y  = body-Y = forward
    out[2] = clip1(yaw / gyaw + YAW_COMP * vx);
    out[3] = {s.step_height:.6f}f;                 // normalized step height
    out[4] = b * 2.f - 1.f;
    out[5] = clip1(PR_BASE + PR_SLOPE * speed + PR_YAW * fabsf(yaw));
}}

}}  // namespace tuned_gait
"""
    path = os.path.abspath(path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="\n") as f:
        f.write(body)
    return path, s, lift_mm


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--key", default=TUNED_GAIT_KEY)
    ap.add_argument("--lib", default=LIB)
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()

    lib = json.load(open(args.lib))["gaits"]
    if args.key not in lib:
        raise SystemExit(f"no '{args.key}' in {args.lib}; have: {', '.join(sorted(lib))}")
    path, s, lift = emit(args.key, lib[args.key], args.out)
    print(f"wrote {path}")
    print(f"  key         {args.key}")
    print(f"  stand_frac  {s.duty:.4f}   (firmware tripod: 0.5167, bipod: 0.35)")
    print(f"  offsets     {[round(float(o), 4) for o in s.offsets()]}")
    print(f"  step_height {lift:.1f} mm  (firmware default 15 mm, legacy WALK ceiling 40 mm)")
    print(f"  step_depth  {s.step_depth:.3f} mm   ride {s.ride_mm:+.1f} mm")


if __name__ == "__main__":
    main()
